### ISSUE TITLE
How to set width table to 100%?

### ISSUE THREAD

**Issue by abdonrd** [carbon-design-system/carbon-custom-elements#279]
Simple question: how to set width data-table to 100%?

This doesn't work:
```css
bx-table {
  width: 100%;
}
```
